[server]
port="8001"
addr="localhost"
readTimeout=5
writeTimeout=5
closeTimeout=5

[cors]
allowed_origins=["*"]
allowed_methods=["*"]
allow_credentials=true
allowed_headers=["*"]

[logger]
file="log.log"
level="debug"